### ISSUE TITLE
Whoa

### ISSUE THREAD

**Issue by ccorcos** [MyBoon/oro-chat#1]
this is epic. how does it work? how is the video stream bypassing the server?

**Comment by rsylvian** [comment]
Thanks @ccorcos :)
peer.js library is used to handle the video part ... what do you mean by bypassing the server?

**Comment by ccorcos** [comment]
Is the video stream going through the server? Seems like a lot of load... Or is it going directly the other persons browser?

**Comment by rsylvian** [comment]
Yes that's p2p ... no server involved :)
