### ISSUE TITLE
Support for mobile (Cordova)

### ISSUE THREAD

**Issue by xpluscal** [MyBoon/oro-chat#2]
Hey there,
are there any plans to integrate mobile/Cordova support?

Thanks

**Comment by rsylvian** [comment]
Hi @xpluscal!
Never thought about this but that will be so cool indeed 👍 

That being said, I don't plan on integrating with Meteor Mobile but I'll be happy to help if you decide to do it.

**Comment by rsylvian** [comment]
Closing the issue since it's more a request than anything else. Thanks for the suggestion!
