### ISSUE TITLE
Getting errors and not showing anything on the browser window.

### ISSUE THREAD

**Issue by mesameen** [MyBoon/oro-chat#3]
![image](https://cloud.githubusercontent.com/assets/15923204/16177405/dc6290d2-3649-11e6-9c72-9d767ef99e0c.png)

**Comment by rsylvian** [comment]
Hi @sandeepmeenuga! Thanks for your report.
What version of meteor are you using? It looks like `call` is a reserved word now ... 

I'll fix this.

**Comment by rsylvian** [comment]
@sandeepmeenuga: Just pushed the fix on master. Closing the issue now.
